// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: tei.proto

package nlp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Info_Info_FullMethodName = "/tei.v1.Info/Info"
)

// InfoClient is the client API for Info service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InfoClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type infoClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoClient(cc grpc.ClientConnInterface) InfoClient {
	return &infoClient{cc}
}

func (c *infoClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, Info_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoServer is the server API for Info service.
// All implementations must embed UnimplementedInfoServer
// for forward compatibility.
type InfoServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedInfoServer()
}

// UnimplementedInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInfoServer struct{}

func (UnimplementedInfoServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedInfoServer) mustEmbedUnimplementedInfoServer() {}
func (UnimplementedInfoServer) testEmbeddedByValue()              {}

// UnsafeInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfoServer will
// result in compilation errors.
type UnsafeInfoServer interface {
	mustEmbedUnimplementedInfoServer()
}

func RegisterInfoServer(s grpc.ServiceRegistrar, srv InfoServer) {
	// If the following call pancis, it indicates UnimplementedInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Info_ServiceDesc, srv)
}

func _Info_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Info_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Info_ServiceDesc is the grpc.ServiceDesc for Info service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Info_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tei.v1.Info",
	HandlerType: (*InfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Info_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tei.proto",
}

const (
	Embed_Embed_FullMethodName             = "/tei.v1.Embed/Embed"
	Embed_EmbedStream_FullMethodName       = "/tei.v1.Embed/EmbedStream"
	Embed_EmbedSparse_FullMethodName       = "/tei.v1.Embed/EmbedSparse"
	Embed_EmbedSparseStream_FullMethodName = "/tei.v1.Embed/EmbedSparseStream"
	Embed_EmbedAll_FullMethodName          = "/tei.v1.Embed/EmbedAll"
	Embed_EmbedAllStream_FullMethodName    = "/tei.v1.Embed/EmbedAllStream"
)

// EmbedClient is the client API for Embed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbedClient interface {
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	EmbedStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbedRequest, EmbedResponse], error)
	EmbedSparse(ctx context.Context, in *EmbedSparseRequest, opts ...grpc.CallOption) (*EmbedSparseResponse, error)
	EmbedSparseStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbedSparseRequest, EmbedSparseResponse], error)
	EmbedAll(ctx context.Context, in *EmbedAllRequest, opts ...grpc.CallOption) (*EmbedAllResponse, error)
	EmbedAllStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbedAllRequest, EmbedAllResponse], error)
}

type embedClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbedClient(cc grpc.ClientConnInterface) EmbedClient {
	return &embedClient{cc}
}

func (c *embedClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, Embed_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embedClient) EmbedStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbedRequest, EmbedResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Embed_ServiceDesc.Streams[0], Embed_EmbedStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmbedRequest, EmbedResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Embed_EmbedStreamClient = grpc.BidiStreamingClient[EmbedRequest, EmbedResponse]

func (c *embedClient) EmbedSparse(ctx context.Context, in *EmbedSparseRequest, opts ...grpc.CallOption) (*EmbedSparseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedSparseResponse)
	err := c.cc.Invoke(ctx, Embed_EmbedSparse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embedClient) EmbedSparseStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbedSparseRequest, EmbedSparseResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Embed_ServiceDesc.Streams[1], Embed_EmbedSparseStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmbedSparseRequest, EmbedSparseResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Embed_EmbedSparseStreamClient = grpc.BidiStreamingClient[EmbedSparseRequest, EmbedSparseResponse]

func (c *embedClient) EmbedAll(ctx context.Context, in *EmbedAllRequest, opts ...grpc.CallOption) (*EmbedAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedAllResponse)
	err := c.cc.Invoke(ctx, Embed_EmbedAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embedClient) EmbedAllStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbedAllRequest, EmbedAllResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Embed_ServiceDesc.Streams[2], Embed_EmbedAllStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmbedAllRequest, EmbedAllResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Embed_EmbedAllStreamClient = grpc.BidiStreamingClient[EmbedAllRequest, EmbedAllResponse]

// EmbedServer is the server API for Embed service.
// All implementations must embed UnimplementedEmbedServer
// for forward compatibility.
type EmbedServer interface {
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	EmbedStream(grpc.BidiStreamingServer[EmbedRequest, EmbedResponse]) error
	EmbedSparse(context.Context, *EmbedSparseRequest) (*EmbedSparseResponse, error)
	EmbedSparseStream(grpc.BidiStreamingServer[EmbedSparseRequest, EmbedSparseResponse]) error
	EmbedAll(context.Context, *EmbedAllRequest) (*EmbedAllResponse, error)
	EmbedAllStream(grpc.BidiStreamingServer[EmbedAllRequest, EmbedAllResponse]) error
	mustEmbedUnimplementedEmbedServer()
}

// UnimplementedEmbedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmbedServer struct{}

func (UnimplementedEmbedServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedEmbedServer) EmbedStream(grpc.BidiStreamingServer[EmbedRequest, EmbedResponse]) error {
	return status.Errorf(codes.Unimplemented, "method EmbedStream not implemented")
}
func (UnimplementedEmbedServer) EmbedSparse(context.Context, *EmbedSparseRequest) (*EmbedSparseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmbedSparse not implemented")
}
func (UnimplementedEmbedServer) EmbedSparseStream(grpc.BidiStreamingServer[EmbedSparseRequest, EmbedSparseResponse]) error {
	return status.Errorf(codes.Unimplemented, "method EmbedSparseStream not implemented")
}
func (UnimplementedEmbedServer) EmbedAll(context.Context, *EmbedAllRequest) (*EmbedAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmbedAll not implemented")
}
func (UnimplementedEmbedServer) EmbedAllStream(grpc.BidiStreamingServer[EmbedAllRequest, EmbedAllResponse]) error {
	return status.Errorf(codes.Unimplemented, "method EmbedAllStream not implemented")
}
func (UnimplementedEmbedServer) mustEmbedUnimplementedEmbedServer() {}
func (UnimplementedEmbedServer) testEmbeddedByValue()               {}

// UnsafeEmbedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbedServer will
// result in compilation errors.
type UnsafeEmbedServer interface {
	mustEmbedUnimplementedEmbedServer()
}

func RegisterEmbedServer(s grpc.ServiceRegistrar, srv EmbedServer) {
	// If the following call pancis, it indicates UnimplementedEmbedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Embed_ServiceDesc, srv)
}

func _Embed_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Embed_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Embed_EmbedStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmbedServer).EmbedStream(&grpc.GenericServerStream[EmbedRequest, EmbedResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Embed_EmbedStreamServer = grpc.BidiStreamingServer[EmbedRequest, EmbedResponse]

func _Embed_EmbedSparse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedSparseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedServer).EmbedSparse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Embed_EmbedSparse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedServer).EmbedSparse(ctx, req.(*EmbedSparseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Embed_EmbedSparseStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmbedServer).EmbedSparseStream(&grpc.GenericServerStream[EmbedSparseRequest, EmbedSparseResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Embed_EmbedSparseStreamServer = grpc.BidiStreamingServer[EmbedSparseRequest, EmbedSparseResponse]

func _Embed_EmbedAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedServer).EmbedAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Embed_EmbedAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedServer).EmbedAll(ctx, req.(*EmbedAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Embed_EmbedAllStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmbedServer).EmbedAllStream(&grpc.GenericServerStream[EmbedAllRequest, EmbedAllResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Embed_EmbedAllStreamServer = grpc.BidiStreamingServer[EmbedAllRequest, EmbedAllResponse]

// Embed_ServiceDesc is the grpc.ServiceDesc for Embed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Embed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tei.v1.Embed",
	HandlerType: (*EmbedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _Embed_Embed_Handler,
		},
		{
			MethodName: "EmbedSparse",
			Handler:    _Embed_EmbedSparse_Handler,
		},
		{
			MethodName: "EmbedAll",
			Handler:    _Embed_EmbedAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EmbedStream",
			Handler:       _Embed_EmbedStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "EmbedSparseStream",
			Handler:       _Embed_EmbedSparseStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "EmbedAllStream",
			Handler:       _Embed_EmbedAllStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tei.proto",
}

const (
	Predict_Predict_FullMethodName           = "/tei.v1.Predict/Predict"
	Predict_PredictPair_FullMethodName       = "/tei.v1.Predict/PredictPair"
	Predict_PredictStream_FullMethodName     = "/tei.v1.Predict/PredictStream"
	Predict_PredictPairStream_FullMethodName = "/tei.v1.Predict/PredictPairStream"
)

// PredictClient is the client API for Predict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PredictClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	PredictPair(ctx context.Context, in *PredictPairRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	PredictStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PredictRequest, PredictResponse], error)
	PredictPairStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PredictPairRequest, PredictResponse], error)
}

type predictClient struct {
	cc grpc.ClientConnInterface
}

func NewPredictClient(cc grpc.ClientConnInterface) PredictClient {
	return &predictClient{cc}
}

func (c *predictClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, Predict_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictClient) PredictPair(ctx context.Context, in *PredictPairRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, Predict_PredictPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictClient) PredictStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PredictRequest, PredictResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Predict_ServiceDesc.Streams[0], Predict_PredictStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PredictRequest, PredictResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Predict_PredictStreamClient = grpc.BidiStreamingClient[PredictRequest, PredictResponse]

func (c *predictClient) PredictPairStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PredictPairRequest, PredictResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Predict_ServiceDesc.Streams[1], Predict_PredictPairStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PredictPairRequest, PredictResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Predict_PredictPairStreamClient = grpc.BidiStreamingClient[PredictPairRequest, PredictResponse]

// PredictServer is the server API for Predict service.
// All implementations must embed UnimplementedPredictServer
// for forward compatibility.
type PredictServer interface {
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	PredictPair(context.Context, *PredictPairRequest) (*PredictResponse, error)
	PredictStream(grpc.BidiStreamingServer[PredictRequest, PredictResponse]) error
	PredictPairStream(grpc.BidiStreamingServer[PredictPairRequest, PredictResponse]) error
	mustEmbedUnimplementedPredictServer()
}

// UnimplementedPredictServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPredictServer struct{}

func (UnimplementedPredictServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedPredictServer) PredictPair(context.Context, *PredictPairRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictPair not implemented")
}
func (UnimplementedPredictServer) PredictStream(grpc.BidiStreamingServer[PredictRequest, PredictResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PredictStream not implemented")
}
func (UnimplementedPredictServer) PredictPairStream(grpc.BidiStreamingServer[PredictPairRequest, PredictResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PredictPairStream not implemented")
}
func (UnimplementedPredictServer) mustEmbedUnimplementedPredictServer() {}
func (UnimplementedPredictServer) testEmbeddedByValue()                 {}

// UnsafePredictServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PredictServer will
// result in compilation errors.
type UnsafePredictServer interface {
	mustEmbedUnimplementedPredictServer()
}

func RegisterPredictServer(s grpc.ServiceRegistrar, srv PredictServer) {
	// If the following call pancis, it indicates UnimplementedPredictServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Predict_ServiceDesc, srv)
}

func _Predict_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Predict_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Predict_PredictPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).PredictPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Predict_PredictPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).PredictPair(ctx, req.(*PredictPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Predict_PredictStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PredictServer).PredictStream(&grpc.GenericServerStream[PredictRequest, PredictResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Predict_PredictStreamServer = grpc.BidiStreamingServer[PredictRequest, PredictResponse]

func _Predict_PredictPairStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PredictServer).PredictPairStream(&grpc.GenericServerStream[PredictPairRequest, PredictResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Predict_PredictPairStreamServer = grpc.BidiStreamingServer[PredictPairRequest, PredictResponse]

// Predict_ServiceDesc is the grpc.ServiceDesc for Predict service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Predict_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tei.v1.Predict",
	HandlerType: (*PredictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _Predict_Predict_Handler,
		},
		{
			MethodName: "PredictPair",
			Handler:    _Predict_PredictPair_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PredictStream",
			Handler:       _Predict_PredictStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PredictPairStream",
			Handler:       _Predict_PredictPairStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tei.proto",
}

const (
	Rerank_Rerank_FullMethodName       = "/tei.v1.Rerank/Rerank"
	Rerank_RerankStream_FullMethodName = "/tei.v1.Rerank/RerankStream"
)

// RerankClient is the client API for Rerank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RerankClient interface {
	Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error)
	RerankStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RerankStreamRequest, RerankResponse], error)
}

type rerankClient struct {
	cc grpc.ClientConnInterface
}

func NewRerankClient(cc grpc.ClientConnInterface) RerankClient {
	return &rerankClient{cc}
}

func (c *rerankClient) Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RerankResponse)
	err := c.cc.Invoke(ctx, Rerank_Rerank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rerankClient) RerankStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RerankStreamRequest, RerankResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Rerank_ServiceDesc.Streams[0], Rerank_RerankStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RerankStreamRequest, RerankResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rerank_RerankStreamClient = grpc.ClientStreamingClient[RerankStreamRequest, RerankResponse]

// RerankServer is the server API for Rerank service.
// All implementations must embed UnimplementedRerankServer
// for forward compatibility.
type RerankServer interface {
	Rerank(context.Context, *RerankRequest) (*RerankResponse, error)
	RerankStream(grpc.ClientStreamingServer[RerankStreamRequest, RerankResponse]) error
	mustEmbedUnimplementedRerankServer()
}

// UnimplementedRerankServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRerankServer struct{}

func (UnimplementedRerankServer) Rerank(context.Context, *RerankRequest) (*RerankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rerank not implemented")
}
func (UnimplementedRerankServer) RerankStream(grpc.ClientStreamingServer[RerankStreamRequest, RerankResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RerankStream not implemented")
}
func (UnimplementedRerankServer) mustEmbedUnimplementedRerankServer() {}
func (UnimplementedRerankServer) testEmbeddedByValue()                {}

// UnsafeRerankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RerankServer will
// result in compilation errors.
type UnsafeRerankServer interface {
	mustEmbedUnimplementedRerankServer()
}

func RegisterRerankServer(s grpc.ServiceRegistrar, srv RerankServer) {
	// If the following call pancis, it indicates UnimplementedRerankServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rerank_ServiceDesc, srv)
}

func _Rerank_Rerank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RerankServer).Rerank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rerank_Rerank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RerankServer).Rerank(ctx, req.(*RerankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rerank_RerankStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RerankServer).RerankStream(&grpc.GenericServerStream[RerankStreamRequest, RerankResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rerank_RerankStreamServer = grpc.ClientStreamingServer[RerankStreamRequest, RerankResponse]

// Rerank_ServiceDesc is the grpc.ServiceDesc for Rerank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rerank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tei.v1.Rerank",
	HandlerType: (*RerankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rerank",
			Handler:    _Rerank_Rerank_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RerankStream",
			Handler:       _Rerank_RerankStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "tei.proto",
}

const (
	Tokenize_Tokenize_FullMethodName       = "/tei.v1.Tokenize/Tokenize"
	Tokenize_TokenizeStream_FullMethodName = "/tei.v1.Tokenize/TokenizeStream"
	Tokenize_Decode_FullMethodName         = "/tei.v1.Tokenize/Decode"
	Tokenize_DecodeStream_FullMethodName   = "/tei.v1.Tokenize/DecodeStream"
)

// TokenizeClient is the client API for Tokenize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenizeClient interface {
	Tokenize(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error)
	TokenizeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EncodeRequest, EncodeResponse], error)
	Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error)
	DecodeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DecodeRequest, DecodeResponse], error)
}

type tokenizeClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenizeClient(cc grpc.ClientConnInterface) TokenizeClient {
	return &tokenizeClient{cc}
}

func (c *tokenizeClient) Tokenize(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodeResponse)
	err := c.cc.Invoke(ctx, Tokenize_Tokenize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizeClient) TokenizeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EncodeRequest, EncodeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tokenize_ServiceDesc.Streams[0], Tokenize_TokenizeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EncodeRequest, EncodeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tokenize_TokenizeStreamClient = grpc.BidiStreamingClient[EncodeRequest, EncodeResponse]

func (c *tokenizeClient) Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeResponse)
	err := c.cc.Invoke(ctx, Tokenize_Decode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizeClient) DecodeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DecodeRequest, DecodeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tokenize_ServiceDesc.Streams[1], Tokenize_DecodeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DecodeRequest, DecodeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tokenize_DecodeStreamClient = grpc.BidiStreamingClient[DecodeRequest, DecodeResponse]

// TokenizeServer is the server API for Tokenize service.
// All implementations must embed UnimplementedTokenizeServer
// for forward compatibility.
type TokenizeServer interface {
	Tokenize(context.Context, *EncodeRequest) (*EncodeResponse, error)
	TokenizeStream(grpc.BidiStreamingServer[EncodeRequest, EncodeResponse]) error
	Decode(context.Context, *DecodeRequest) (*DecodeResponse, error)
	DecodeStream(grpc.BidiStreamingServer[DecodeRequest, DecodeResponse]) error
	mustEmbedUnimplementedTokenizeServer()
}

// UnimplementedTokenizeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenizeServer struct{}

func (UnimplementedTokenizeServer) Tokenize(context.Context, *EncodeRequest) (*EncodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tokenize not implemented")
}
func (UnimplementedTokenizeServer) TokenizeStream(grpc.BidiStreamingServer[EncodeRequest, EncodeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method TokenizeStream not implemented")
}
func (UnimplementedTokenizeServer) Decode(context.Context, *DecodeRequest) (*DecodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decode not implemented")
}
func (UnimplementedTokenizeServer) DecodeStream(grpc.BidiStreamingServer[DecodeRequest, DecodeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DecodeStream not implemented")
}
func (UnimplementedTokenizeServer) mustEmbedUnimplementedTokenizeServer() {}
func (UnimplementedTokenizeServer) testEmbeddedByValue()                  {}

// UnsafeTokenizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenizeServer will
// result in compilation errors.
type UnsafeTokenizeServer interface {
	mustEmbedUnimplementedTokenizeServer()
}

func RegisterTokenizeServer(s grpc.ServiceRegistrar, srv TokenizeServer) {
	// If the following call pancis, it indicates UnimplementedTokenizeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tokenize_ServiceDesc, srv)
}

func _Tokenize_Tokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizeServer).Tokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tokenize_Tokenize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizeServer).Tokenize(ctx, req.(*EncodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tokenize_TokenizeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TokenizeServer).TokenizeStream(&grpc.GenericServerStream[EncodeRequest, EncodeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tokenize_TokenizeStreamServer = grpc.BidiStreamingServer[EncodeRequest, EncodeResponse]

func _Tokenize_Decode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizeServer).Decode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tokenize_Decode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizeServer).Decode(ctx, req.(*DecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tokenize_DecodeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TokenizeServer).DecodeStream(&grpc.GenericServerStream[DecodeRequest, DecodeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tokenize_DecodeStreamServer = grpc.BidiStreamingServer[DecodeRequest, DecodeResponse]

// Tokenize_ServiceDesc is the grpc.ServiceDesc for Tokenize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tokenize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tei.v1.Tokenize",
	HandlerType: (*TokenizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tokenize",
			Handler:    _Tokenize_Tokenize_Handler,
		},
		{
			MethodName: "Decode",
			Handler:    _Tokenize_Decode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TokenizeStream",
			Handler:       _Tokenize_TokenizeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DecodeStream",
			Handler:       _Tokenize_DecodeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tei.proto",
}
