version: "3.9"

services:
  tei:
    build:
      context: .
      dockerfile: TEI-Dockerfile
    image: tei:local
    ports:
      - "10000:10000"
    networks:
      - beansack-net

  beansapi:
    build: 
      context: .
      dockerfile: Dockerfile
    image: beans-api:local
    ports:
      - "8080:8080"
    volumes:
      - ./.beansack:/app/data
    environment:
      - PORT=8080
      - EMBEDDER_BASE_URL=tei:10000
    env_file:
      - .env
    depends_on:
      - tei
    networks:
      - beansack-net

networks:
  beansack-net:
    driver: bridge
