# fly.toml app configuration file generated for beansack-api on 2025-09-05T17:03:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beansack-api'
primary_region = 'iad'

[build]
    dockerfile = 'Dockerfile'
    ignorefile = '.dockerignore'

[http_service]
    internal_port = 8080
    force_https = true
    auto_stop_machines = 'stop'
    auto_start_machines = true
    min_machines_running = 0
    max_machines_running = 1
    processes = ['app']

[[vm]]
    size = "shared-cpu-4x"
    memory = '5gb'
    cpu_kind = 'shared'
    cpus = 4

[mounts]
    source = "beansack_data"
    destination = "/data"